# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

qr_Q <- function(x) {
    .Call(`_RandClust_qr_Q`, x)
}

rsample <- function(A, P) {
    .Call(`_RandClust_rsample`, A, P)
}

spbin_prod <- function(Ai, Aj, P) {
    .Call(`_RandClust_spbin_prod`, Ai, Aj, P)
}

spbin_crossprod <- function(Ai, Aj, P) {
    .Call(`_RandClust_spbin_crossprod`, Ai, Aj, P)
}

